# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-23 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=20, verbose_name='宝贝名称')),
                ('desc', models.CharField(max_length=200, verbose_name='宝贝简介')),
                ('detail', tinymce.models.HTMLField(verbose_name='商品详情')),
                ('image', models.ImageField(upload_to='Goods', verbose_name='图片')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('type_id', models.SmallIntegerField(choices=[(1, '书籍资料'), (2, '手机数码'), (3, '交通工具'), (4, '美妆服饰'), (5, '兴趣特长'), (6, '日用百货')], default=2, verbose_name='分类')),
                ('trade_way', models.SmallIntegerField(choices=[(0, '自提'), (1, '面交'), (2, '邮寄')], default=2, verbose_name='交易方式')),
                ('stock', models.IntegerField(default=1, verbose_name='数量')),
                ('status', models.SmallIntegerField(choices=[(0, '下线'), (1, '上线')], default=1, verbose_name='状态')),
            ],
            options={
                'db_table': 's_goods',
                'verbose_name': '宝贝',
                'verbose_name_plural': '宝贝',
            },
        ),
    ]
