# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-28 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0002_goods_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='sales',
            field=models.IntegerField(default=0, verbose_name='销量'),
        ),
    ]
