# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-28 08:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_auto_20190328_0817'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderGooks',
            new_name='OrderGoods',
        ),
    ]
